apiVersion: apps/v1
kind: Deployment
metadata:
  name: interop-sequencer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interop-sequencer
  template:
    metadata:
      labels:
        app: interop-sequencer
    spec:
      containers:
        - name: sequencer
          image: interop/sequencer:latest
          ports:
            - containerPort: 9090
